management:
    endpoints:
        web:
            exposure:
                include: "*"

cds:
    sql.hana.search:
        fuzzy: true
        fuzzinessThreshold: 0.9
    security.mock.users:
    - name: rose
    - name: martha
      roles:
        - reviewer
    - name: amy
      roles:
        - processor
        - cds.Developer
    - name: admin
      password: admin
      roles:
      - admin
      - cds.Developer

    odata-v4:
        endpoint:
            path: "/"

---
spring:
    config.activate.on-profile: default
    sql.init.platform: h2

server:
    port: 4004

---
spring:
    config.activate.on-profile: cloud

---
#logging.level.org.springframework: DEBUG
logging:
  level:
    com:
      sap:
        cds:
          framework:
            spring:
              config:
                auth:
                  mock: OFF

          services:
            impl:
              persistence: OFF
              utils: OFF